import Head from 'next/head'

export async function getStaticProps({ preview = false }) {
  return {
    props: {
      preview,
    },
  }
}

export default function Home() {
  // const preview = previewData()

  // if (preview) {
  //   return 'PREVIEW'
  // }

  // const {data} =  useGetPostsQuery()

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="py-16">
        <h1 className="bg-gradient-to-r from-[#007CF0] to-[#00DFD8] bg-clip-text text-center text-7xl font-black text-transparent">
          My Awesome Home
        </h1>
      </section>
    </>
  )
}
